leonardssh/vscord

src/languages.json
This addition is necessary to detect shellscripts without an extension as such.
Quite commonly shellscripts are not identified by a `.sh` extension but by a `#!/bin/sh` shebang and no extension (e.g. a script simply called `build`) which vscode detects as the languageId "shellscript".
Currently those files would just be displayed as txt files by the extension which is fixed by this pr.
It's late and this simple detail bothered my sleepy mind so yeah lmfao
=> feat(languages.json): add shellscript to KNOWN_LANGUAGES

package.json
Don't run activate functions on every activation event.
Reduces lag caused by activating or installing the extension.
=> Activate with the `onStartupFinished` event only

.github/workflows/cd.yml
The extension will be deployed to the Open VSX registry and the Visual Studio Marketplace. The
workflow will be started on the creation of new git tags in the main branch.
fix #29
1. Create an Eclipse account
2. Log in and sign the Publisher Agreement
3. Create an access token
4. Create the namespace
5. Add both tokens to the repository secrets
6. Merge this PR
[Open VSX wiki: “Publishing Extensions”](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)  
[GitHub's docs: “Encrypted secrets”](https://docs.github.com/en/actions/security-guides/encrypted-secrets)
=> feat CD: Use GitHub actions to deploy the extension

src/languages.json
- I added **Ansible** to the languages as it uses `yaml` files
- I added a missing extension for **Jinja**
=> Add Ansible language and missing extension for Jinja

src/data/languages.json
Add NPM icon to `package.json` and `.npmignore`
fix #54
=> NPM icon for related extensions

package.json, src/activity.ts, src/constants.ts
This PR adds a new config option to hide the view repo button based on the git host.
The use case is preventing the display of a git host e.g. used for work that might have your legal name
as the username..
This way you can essentially opt in to the repository button for your public profile but preserve your real name from being doxxed.
=> feat: add option to ignore git hosts

src/helpers/getApplicationId.ts
- Use Map constructor.
- Automatically generate regex from Map.
=> refactor: `getApplicationId()`

README.md, package.json, src/activity.ts, src/config.ts, src/constants.ts
The main issue I see is the `vscord.status.problems.countedSeveritie` and how it based of an array of user defined variables it defaults to errors and warnings but if the user does not define this correctly it wont work. Dont really know a better way of doing this in vscode config. Was thinking maybe multiple checkbox select thing but I dont think vsocde supports something like that
=> Advanced problem config

src/controller.ts, src/data.ts
The issue was that when it failed rpc set the instance to false. Force setting instance to true when activity is sent means that it should never be in a state where it wont work. After reconnecting from a connection timeout error or other from Discord rpc the plugin should still be able to reconnect and work
Closes #145 & #111
=> fix(#145, #111): force set instance to true when sending activity

src/controller.ts
This issue may have something to do with `if (this.client.isConnected && this.client.clientId === clientId) return;` also not destroying correctly when this occurs. This will give us enougth logs to figure out what is going on. It looks like the catch doesnt even get hit by this this is why i assume it something to do with this.
After this is resolved we can remove the massive this.client logs
=> devops: Added extra debug for issue: #145

src/controller.ts, src/extension.ts
Before - if there were to be a discord gateway connection fail. The tooltip would disappear and if one were to close the popup to reconnect to the gateway - they would have to use the Command Prompt. Also if the connection failed on retry, the tooltip would disappear altogether.
This change makes it easier by always showing the tooltip and just ammending the message based on a failed connection. It appears on the pop up to reconnect to the gateway and appears on the error handler with a window error message.
=> Show the StatusBar on Discord Gateway Connection Fail.

src/activity.ts
Fixes the main issue raised in #197.
The logic for selecting current state was slightly off, and it would lead to the first button having very weird behavior (more details in the issue).
=> Fix activity state logic (#197)

src/data/languages.json
=> fix(#256): Adds tailwind support for typescript (.ts, .cts, .mts)

package.json
deprecate(config): `contributes.configuration`: `vscord.enabled`
Having a contributes.configuration property for an extension enablement state is redundant to the [built-in setting](redundant) and a bad practice
=> deprecate(config): `contributes.configuration`: `vscord.enabled`

.github/workflows/CI.yml, .vscode/settings.json, ADDING_LANGUAGE.md, package.json, pnpm-lock.yaml, src/activity.ts, src/config.ts, src/constants.ts, src/controller.ts, src/editor.ts, src/extension.ts, src/helpers/getFileSize.ts
* Added Prettier as the default code formatter (.vscode/settings.json).
* Now we can build & lint project without installing `vsce`, `prettier` as global command line clients.
```jsonc
// ...
"scripts": {
"vscode:prepublish": "pnpm tsup",         // builds typescript without checks
"package": "pnpm vsce package --no-yarn", // .vsix file building
"watch": "pnpm tsup --watch",
"lint": "pnpm prettier . --check",        // show unformatted files
"lint:fix": "pnpm prettier . --write"     // format files
}
// ...
```
* Package dependencies.
* Added.
* `@vscode/vsce@^2.22.0` should be used by contributors and GitHub Actions via the `pnpm package` command.
* Updated CI configuration. It now uses `pnpm package` command.
* Updated.
* `@types/git-url-parse` - `^9.0.1 -> ^9.0.3`.
* `typescript` - …
=> Improved, fixed, added

src/data.ts
I've seen that there's already a solution for getting rid of [SSH] tag in workspace name, so I added support for [WSL] tags
=> Remove annoying [WSL: Ubuntu] from workspace name

src/data/languages.json
This file type is used for the Soong build system in Android. It does not have an official icon, so the Android icon should be ok. 
Read more about it [here](https://source.android.com/docs/setup/reference/androidbp).
=> Feature: add Android Blueprint (.bp)

README.md, src/activity.ts
This PR adds a new variable, `{git_urlname}`, as an alternative to `{git_url}`
Since discord doesn't linkify URLs in the rich presence text, the `https://` in front of the URL is just visual clutter
=> Feature: add {git_urlname}

README.md, src/activity.ts
If you use the git url in your description, having the workspace folder in front of the file's path is kinda redundant, and takes away precious space.
This PR adds `{relative_filepath}`, which is exactly `{full_directory_name}/{file_name}.{file_extension}` but without the workspace folder in front
=> Feature: add {relative_filepath}

README.md
The title speaks for itself.
This pull request will also remove (annoying) blue[ ](#)underlining[ ](#)between[ ](#)shields. I used [reference-style links][1], however I couldn't come up with more readable names, so feel free to change them. 🤷‍♂️
[1]: https://www.markdownguide.org/basic-syntax/#reference-style-links
=> Minimize the use of HTML in README.md

package.json, src/activity.ts, src/config.ts, src/constants.ts
Adds a new option to settings (vscord.status.state.debugging.enabled). It is enabled by default
When disabled, it will not detect whether you are debugging a file or not.
=> feat: add an option to disable the debugging status

package.json
Closes #318, Closes #297, Closes #170
VSCord should now wait for vscode.git to be completely loaded now.
=> Fix: Added vscode.git as a dependency of vscord

package.json, src/activity.ts, src/controller.ts
This pull request fixes a problem which caused `DisconnectOnIdle` option to never re-connect RPC after disconnecting due to some refactoring that happened in the extension shortly after I implemented the option.
Instead of calling `.disable()`, I modified `checkCanSend` to disallow presence when idling if the option is enabled. A subtle improvement to how timer resets after idling was also needed.
Additionally to this, I added some explanations on what idle-related settings do exactly, as they sounded kinda similar and it wasn't clear what they did exactly.
https://github.com/leonardssh/vscord/assets/19842935/aa59a8e8-4223-4545-8502-2fe0771fb198
=> Fix(#162): `DisconnectOnIdle` doesn't restore presence 

README.md, src/activity.ts, src/helpers/resolveLangName.ts
Adds variables `{a_lang}`, {a_Lang} and {a_LANG}. These do the exact same thing as `{lang}`, {Lang} and {LANG}, except they prefix the value with "a " or "an " depending on if the language name starts with a vowel.
**Examples:**
`{a_lang}`:
`{a_Lang}`:
`{a_LANG}`:
=> (feat)Add article prefix support for language variables

package.json, src/config.ts, src/constants.ts, src/controller.ts
Add setting in config to suppress the `RPC: RPC_COULD_NOT_CONNECT` error.
Useful if Discord is not permanently running (e.g. no auto start-up)
=> Add configuration option to suppress RPC connection error notifications
